CTFd/CTFd/admin/__init__.py
import csv
import datetime
import os

import six
from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

from CTFd.cache import cache, clear_config
from CTFd.models import (
    Awards,
    Configs,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
    get_class_by_tablename,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_config, set_config
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.exports import import_ctf as import_ctf_util
from CTFd.utils.helpers import get_errors
from CTFd.utils.security.auth import logout_user
from CTFd.utils.user import is_admin

admin = Blueprint("admin", __name__)

from CTFd.admin import challenges  # noqa: F401
from CTFd.admin import notifications  # noqa: F401
from CTFd.admin import pages  # noqa: F401
from CTFd.admin import scoreboard  # noqa: F401
from CTFd.admin import statistics  # noqa: F401
from CTFd.admin import submissions  # noqa: F401
from CTFd.admin import teams  # noqa: F401
from CTFd.admin import users  # noqa: F401


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["POST"])
@admins_only
def import_ctf():
    backup = request.files["backup"]
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for("admin.config"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    # TODO: It might make sense to limit dumpable tables. Config could potentially leak sensitive information.
    model = get_class_by_tablename(table)
    if model is None:
        abort(404)

    temp = six.StringIO()
    writer = csv.writer(temp)

    header = [column.name for column in model.__mapper__.columns]
    writer.writerow(header)

    responses = model.query.all()

    for curr in responses:
        writer.writerow(
            [getattr(curr, column.name) for column in model.__mapper__.columns]
        )

    temp.seek(0)

    # In Python 3 send_file requires bytes
    output = six.BytesIO()
    output.write(temp.getvalue().encode("utf-8"))
    output.seek(0)
    temp.close()

    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    database_tables = sorted(db.metadata.tables.keys())

    configs = Configs.query.all()
    configs = dict([(c.key, get_config(c.key)) for c in configs])

    themes = ctf_config.get_themes()
    themes.remove(get_config("ctf_theme"))

    return render_template(
        "admin/config.html", database_tables=database_tables, themes=themes, **configs
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        # Truncate Users, Teams, Submissions, Solves, Notifications, Awards, Unlocks, Tracking
        Tracking.query.delete()
        Solves.query.delete()
        Submissions.query.delete()
        Awards.query.delete()
        Unlocks.query.delete()
        Users.query.delete()
        Teams.query.delete()
        set_config("setup", False)
        db.session.commit()
        cache.clear()
        logout_user()
        db.session.close()
        return redirect(url_for("views.setup"))

    return render_template("admin/reset.html")

CTFd/CTFd/api/v1/statistics/__init__.py
from flask_restplus import Namespace

statistics_namespace = Namespace(
    "statistics", description="Endpoint to retrieve Statistics"
)

from CTFd.api.v1.statistics import challenges  # noqa: F401
from CTFd.api.v1.statistics import submissions  # noqa: F401
from CTFd.api.v1.statistics import teams  # noqa: F401
from CTFd.api.v1.statistics import users  # noqa: F401

CTFd/CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.utils import get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

CTFd/CTFd/themes/admin/templates/base.html
<!DOCTYPE html>
<html>

<head>
	<title>Admin Panel</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{{ url_for('views.themes', theme='core', path='img/favicon.ico') }}" type="image/x-icon">
	<link rel="icon" href="{{ url_for('views.themes', theme='core', path='img/favicon.ico') }}" type="image/x-icon">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='core', path='css/fonts.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='core', path='css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='admin', path='css/admin.css') }}">
	<script type="text/javascript">
		var init = {
			'urlRoot': "{{ request.script_root }}",
			'csrfNonce': "{{ nonce }}",
			'userMode': "{{ get_config('user_mode') }}",
			'userId': {{ id if (id is defined) else 0 }},
			'start': {{ get_config("start") | tojson }},
			'end': {{ get_config("end") | tojson }},
		}
	</script>
	{% block stylesheets %} {% endblock %}
	{% for stylesheet in get_registered_admin_stylesheets() %}
		{% if stylesheet.startswith('http') %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% elif request.script_root %}
			<link rel="stylesheet" type="text/css" href="{{ request.script_root }}/{{ stylesheet }}">
		{% else %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% endif %}
	{% endfor %}
</head>

<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<div class="container">
			<a href="{{ url_for('views.static_html', route='/') }}" class="navbar-brand">CTFd</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#base-navbars"
					aria-controls="base-navbars" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="base-navbars">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.statistics') }}">Statistics</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.notifications') }}">Notifications</a>
					</li>
					<li class="nav-item dropdown">
						<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Pages</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{{ url_for('admin.pages_listing') }}">All Pages</a>
							<a class="dropdown-item" href="{{ url_for('admin.pages_new') }}">New Page</a>
						</div>
					</li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.users_listing') }}">Users</a></li>
					{% if get_config('user_mode') == 'teams' %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.teams_listing') }}">Teams</a></li>
					{% endif %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.scoreboard_listing') }}">Scoreboard</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.challenges_listing') }}">Challenges</a></li>
					<li class="nav-item dropdown">
						<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
						   aria-haspopup="true" aria-expanded="true">Submissions</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{{ url_for('admin.submissions_listing') }}">All Submissions</a>
							<a class="dropdown-item" href="{{ url_for('admin.submissions_listing', submission_type='correct') }}">Correct Submissions</a>
							<a class="dropdown-item" href="{{ url_for('admin.submissions_listing', submission_type='incorrect') }}">Wrong Submissions</a>
						</div>
					</li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.config') }}">Config</a></li>

					{% set plugin_menu = get_admin_plugin_menu_bar() %}
					{% set plugins = get_configurable_plugins() %}
					{% if plugin_menu or plugins %}
						<li class="nav-item">
							<a class="nav-link d-none d-md-block d-lg-block">|</a>
						</li>

						{% for menu in plugin_menu %}
							{% if request.script_root %}
								{% set route = '/' + request.script_root + '/' + menu.route %}
							{% else %}
								{% set route = menu.route %}
							{% endif %}
							<li class="nav-item"><a class="nav-link" href="{{ route }}">{{ menu.title }}</a></li>
						{% endfor %}

						{% if plugins %}
						<li class="nav-item dropdown">
							<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Plugins <span class="caret"></span></a>
							<ul class="dropdown-menu">
									{% for plugin in plugins %}
											<a class="dropdown-item" href="{{ request.script_root }}{{ plugin.route }}">{{ plugin.name }}</a>
									{% endfor %}
							</ul>
						</li>
						{% endif %}
					{% endif %}
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item">
						<a class="nav-link" href="https://help.ctfd.io/" target="_blank">
							<i class="far fa-question-circle"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	{% if get_config('version_latest') %}
	<div class="container-fluid bg-warning text-center py-3">
		<div class="row">
			<div class="col-md-12">
				<a class="btn btn-warning" href="{{ get_config('version_latest') }}">
					A new CTFd version is available!
				</a>
			</div>
		</div>
	</div>
	{% endif %}


	<main role="main">
		{% block content %}
		{% endblock %}
	</main>

	<footer class="footer pt-2">
		<div class="container text-center">
			<a href="https://ctfd.io" class="text-secondary">
				<small class="text-muted">
					Powered by CTFd
				</small>
			</a>
			<span>
				<small class="text-muted"><br> Version {{ get_config('ctf_version') }}</small>
			</span>
		</div>
	</footer>

	<script defer src="{{ url_for('views.themes', theme='admin', path='js/vendor.bundle.js') }}"></script>
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/core.js') }}"></script>
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/helpers.js') }}"></script>

	{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/main.js') }}"></script>
	{% endblock %}

	{% block scripts %} {% endblock %}

	{% for script in get_registered_admin_scripts() %}
		{% if script.startswith('http') %}
			<script defer src="{{ script }}"></script>
		{% elif request.script_root %}
			<script defer src="{{ request.script_root }}/{{ script }}"></script>
		{% else %}
			<script defer src="{{ script }}"></script>
		{% endif %}
	{% endfor %}
</body>

</html>

CTFd/CTFd/themes/admin/templates/config.html
{% extends "admin/base.html" %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Configuration</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<ul class="nav nav-pills flex-column">
				<li class="nav-item">
					<a class="nav-link rounded-0 active" href="#appearance" role="tab" data-toggle="tab">Appearance</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#accounts" role="tab" data-toggle="tab">Accounts</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#mlc" role="tab" data-toggle="tab">MajorLeagueCyber</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#settings" role="tab" data-toggle="tab">Settings</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#email" role="tab" data-toggle="tab">Email</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#ctftime" role="tab" data-toggle="tab">Time</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#backup" role="tab" data-toggle="tab">Backup</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="{{ url_for('admin.reset') }}" role="tab">Reset</a>
				</li>
			</ul>
		</div>
		<div class="col-md-9">
			{% for error in errors %}
				<div class="alert alert-danger alert-dismissable" role="alert">
					<span class="sr-only">Error:</span>
					{{ error }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</div>
			{% endfor %}

			<div class="tab-content">
				{% include "admin/configs/appearance.html" %}

				{% include "admin/configs/accounts.html" %}

				{% include "admin/configs/mlc.html" %}

				{% include "admin/configs/settings.html" %}

				{% include "admin/configs/email.html" %}

				{% include "admin/configs/time.html" %}

				{% include "admin/configs/backup.html" %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/configs.js') }}"></script>
{% endblock %}

CTFd/CTFd/themes/admin/templates/editor.html
{% extends "admin/base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', theme='admin', path='css/codemirror.css') }}">
{% endblock %}

{% block content %}
<div id="media-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h3 class="text-center">Media Library</h3>
						</div>
					</div>
				</div>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="modal-header">
					<div class="container">
						<div class="row mh-100">
							<div class="col-md-6" id="media-library-list">
							</div>
							<div class="col-md-6" id="media-library-details">
								<h4 class="text-center">Media Details</h4>
								<div id="media-item">
									<div class="text-center" id="media-icon">
									</div>
									<br>
									<div class="text-center" id="media-filename">
									</div>
									<br>
									<div class="form-group">
										Link: <input class="form-control" type="text" id="media-link" readonly>
									</div>

									<div class="form-group text-center">
										<div class="row">
											<div class="col-md-6">
												<button class="btn btn-success w-100" id="media-insert"
														data-toggle="tooltip" data-placement="top"
														title="Insert link into editor">
													Insert
												</button>
											</div>
											<div class="col-md-3">
												<button class="btn btn-primary w-100" id="media-download"
														data-toggle="tooltip" data-placement="top"
														title="Download file">
													<i class="fas fa-download"></i>
												</button>
											</div>
											<div class="col-md-3">
												<button class="btn btn-danger w-100" id="media-delete"
														data-toggle="tooltip" data-placement="top"
														title="Delete file">
													<i class="far fa-trash-alt"></i>
												</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<form id="media-library-upload" enctype="multipart/form-data">
					<div class="form-group">
						<label for="media-files">
							Upload Files
						</label>
						<input type="file" name="file" id="media-files" class="form-control-file" multiple>
						<sub class="help-block">
							Attach multiple files using Control+Click or Cmd+Click.
						</sub>
					</div>
					<input type="hidden" value="page" name="type">
				</form>
			</div>
			<div class="modal-footer">
				<div class="float-right">
					<button type="submit" class="btn btn-primary media-upload-button">Upload</button>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<div class="row pt-5">
		<div class="col-md-12">
			<div class="row">
				{% for error in errors %}
					<div class="large-12 large-centered columns">
						<div data-alert class="alert-box alert centered text-center">
							<span>{{ error }}</span>
							<a href="#" class="close">×</a>
						</div>
					</div>
				{% endfor %}
			</div>

			<form id="page-edit" method="POST">
				<div class="form-group">
					<div class="col-md-12">
						<label>
							Title<br>
							<small class="text-muted">This is the title shown on the navigation bar</small>
						</label>
						<input class="form-control radius" id="route" type="text" name="title"
							   value="{% if page is defined %}{{ page.title }}{% endif %}" placeholder="Title">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-12">
						<label>
							Route<br>
							<small class="text-muted">
								This is the URL route that your page will be at (e.g. /page). You can
								also enter links to link to that page.
							</small>
						</label>
						<input class="form-control radius" id="route" type="text" name="route"
							   value="{% if page is defined %}{{ page.route }}{% endif %}" placeholder="Route">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-12">

						<h3>Content</h3>
						<small class="text-muted">This is the HTML content of your page</small>

						<ul class="nav nav-tabs" role="tablist" id="content-edit">
							<li class="nav-item" role="presentation" class="active">
								<a class="nav-link active" href="#content-write" aria-controls="home" role="tab"
								   data-toggle="tab">Write</a>
							</li>
							<li class="nav-item" role="presentation">
								<a class="nav-link preview-page" href="#">Preview</a>
							</li>
						</ul>

						<div class="tab-content">
							<div role="tabpanel" class="tab-pane active" id="content-write" style="height:400px">
								<br>

								<div class="form-inline">
									<div class="btn-group btn-group-sm">
										<div class="btn-group">
											<button type="button" class="btn btn-primary" id="media-button">
												<i class="fas fa-camera-retro"></i>
												Media Library
											</button>
										</div>
									</div>

									<span class="nav-link d-none d-md-block d-lg-block">|</span>

									<div class="form-group pr-3">
										Draft:
										{% set draft = page is defined and page.draft == True %}
										<select class="form-control custom-select" name="draft">
											<option value="true" {% if draft == True %}selected{% endif %}>
												True
											</option>
											<option value="false" {% if draft == False %}selected{% endif %}>
												False
											</option>
										</select>
									</div>

									<div class="form-group pr-3">
										Hidden:
										{% set hidden = page is defined and page.hidden == True %}
										<select class="form-control custom-select" name="hidden">
											<option value="true" {% if hidden == True %}selected{% endif %}>True
											</option>
											<option value="false" {% if hidden == False %}selected{% endif %}>False
											</option>
										</select>
									</div>

									<div class="form-group pr-3">
										Authentication Required:
										{% set auth_required = page is defined and page.auth_required == True %}
										<select class="form-control custom-select" name="auth_required">
											<option value="true" {% if auth_required == True %}selected{% endif %}>
												True
											</option>
											<option value="false" {% if auth_required == False %}selected{% endif %}>
												False
											</option>
										</select>
									</div>
								</div>

								<br>

								<div class="form-group">
									<textarea id="admin-pages-editor" class="d-none"
											  name="content">{% if page is defined %}{{ page.content }}{% endif %}</textarea>
									<input name='id' type='hidden'
										   {% if page is defined %}value="{{ page.id }}"{% endif %}>
								</div>
							</div>
							<div role="tabpanel" class="tab-pane content" id="content-preview" style="height:400px">
							</div>
						</div>
					</div>
				</div>

				<div class="form-group float-right">
					<input name='nonce' type='hidden' value="{{ nonce }}">
					<button class="btn btn-primary" id="save-page">
						{% if page is defined %}
							Update
						{% else %}
							Save
						{% endif %}
					</button>
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/editor.js') }}"></script>
{% endblock %}

CTFd/CTFd/themes/admin/templates/integrations.html
{% extends "base.html" %}

{% block stylesheets %}
<style>
    #base-navbars {
        display: none !important;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-5 text-center">
            <h5>Integration enabled!</h5>
            <p>You may now close this tab.</p>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    localStorage.removeItem('integrations');
    var params = {};
    var pieces = window.location.search
        .substr(1)
        .split("&");
    for (let i = 0; i < pieces.length; i++) {
        var tmp = pieces[i].split("=");
        params[tmp[0]] = tmp[1];
    }
    localStorage.setItem('integrations', JSON.stringify(params));
</script>
{% endblock %}

CTFd/CTFd/themes/admin/templates/notifications.html
{% extends "admin/base.html" %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Notifications</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<form method="POST" id="notifications_form">
					<div class="form-group">
						<label>
							Title
							<small class="form-text text-muted">
								Notification title
							</small>
						</label>
						<input class="form-control" type="text" name="title">
					</div>
					<div class="form-group">
						<label>
							Content
							<small class="form-text text-muted">
								Notification contents can be made up of HTML
							</small>
						</label>
						<textarea class="form-control" type="text" name="content" rows="3"></textarea>
					</div>
					<div class="form-row">
						<div class="col">
							<div class="form-group">
								<label>
									Type
									<small class="form-text text-muted">
										What type of notification users receive
									</small>
								</label>
							</div>
							<div class="form-check form-check-inline pr-1">
								<input class="form-check-input" type="radio" name="type" value="toast" id="type-radio-toast" checked>
								<label class="form-check-label" for="type-radio-toast">Toast</label>
							</div>
							<div class="form-check form-check-inline pr-1">
								<input class="form-check-input" type="radio" name="type" value="alert" id="type-radio-alert">
								<label class="form-check-label" for="type-radio-alert">Alert</label>
							</div>
							<div class="form-check form-check-inline">
								<input class="form-check-input" type="radio" name="type" value="background" id="type-radio-bg">
								<label class="form-check-label" for="type-radio-bg">Background</label>
							</div>
						</div>
						<div class="col">
							<div class="form-group">
								<label>
									Sound
									<small class="form-text text-muted">
										Play sound for users
									</small>
								</label>
							</div>
							<div class="form-check">
								<input class="form-check-input" type="checkbox" name="sound" value="true" id="sound-enable" checked>
								<label class="form-check-label" for="sound-enable">Play Sound</label>
							</div>
						</div>
					</div>
					<div class="float-right">
						<button type="submit" class="btn btn-success text-center">Submit</button>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<hr>
				{% for notification in notifications %}
					<div class="card bg-light mb-4">
						<button type="button" data-notif-id="{{ notification.id }}" class="delete-notification close position-absolute p-3" style="right:0;" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						<div class="card-body">
							<h3 class="card-title">{{ notification.title }}</h3>
							<blockquote class="blockquote mb-0">
								<p>{{ notification.content | safe }}</p>
								<small class="text-muted"><span data-time="{{ notification.date | isoformat }}"></span></small>
							</blockquote>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/notifications.js') }}"></script>
{% endblock %}

CTFd/CTFd/themes/admin/templates/page.html
{% extends "admin/base.html" %}

{% block content %}
	<div class="container">
		{{ content | safe }}
	</div>
{% endblock %}